server:
  port: 80

spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 124.221.132.14
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
