server:
  port: 7011


eureka:
  instance:
    hostname: eureka7011.com  #eureka 服务端的实例名称

  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false # 要不要相互注册
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false # 是否要抓取注册信息
    service-url:
      #集群指向其他eureka
      #defaultZone: http://eureka7012.com:7012/eureka
      #单机就是7001自己
      defaultZone: http://eureka7011.com:7011/eureka
  #server:
    # 默认true，false可以禁用自我保护机制
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000





