server:
  port: 8012

spring:
  application:
    name: springcloud-consumer-order

eureka:
  client:
    #表示自己将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7011/eureka
      defaultZone: http://eureka7011.com:7011/eureka,http://eureka7012.com:7012/eureka
