server:
  port: 8011

spring:
  application:
    name: springcloud-payment-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://:3310/cloud2021?characterEncoding=utf8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    #Druid 配置
    filters: stat
    initial-size: 2 #连接池初始化时初始化的数据库连接数
    max-idle: 10 #最大等待连接中的数量
    min-idle: 1 #最小等待连接中的数量
    max-active: 20 #最大连接数
    #最大等待毫秒数, 单位为 ms, 超过时间会出错误信息
    max-wait: 60000
    # 指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
    time-between-eviction-runs-millis: 60000
    # 指定一个空闲连接最少空闲多久后可被清除
    min-evictable-time-millis: 30000
    #Druid用来测试连接是否可用的SQL语句,默认值每种数据库都不相同：
    validation-query: SELECT '1'
    #如果为true（默认true），当应用向连接池申请连接，并且testOnBorrow为false时，连接池将会判断连接是否处于空闲状态，如果是，则验证这条连接是否可用。
    test-while-idle: true
    #如果为true（默认false），当应用向连接池申请连接时，连接池会判断这条连接是否是可用的。
    test-on-borrow: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.rzk.springcloud.pojo

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7011/eureka
